### <center>Exploração dos Registros de Armas no Brasil</center>

Importando a biblioteca Pandas e verificando a natureza dos dados a primeira vista:

In [4]:
import pandas as pd

data = pd.read_csv("../data/raw/REGISTROS_com_categoria-1965-2004.csv", encoding='latin-1', sep=',')

data

,ANO_EMISSAO,MES_MISSAO,UF,MUNICIPIO,STATUS_REGISTRO,ESPECIE_ARMA,MARCA_ARMA,CALIBRE_ARMA,SEXO,CATEGORIA,TOTAL
0,1965,1,DF,BRASÍLIA,Vencido,Revolver,TAURUS ARMAS S.A.,.38,M,Cidadão,1
1,1965,1,ES,VILA VELHA,Vencido,Revolver,SMITH & WESSON,.32,M,Cidadão,1
2,1965,1,GO,BELA VISTA DE GOIÁS,Vencido,Revolver,TAURUS ARMAS S.A.,.32,M,Cidadão,1
3,1965,1,GO,IPAMERI,Vencido,Carabina,CBC (COMPANHIA BRASILEIRA DE CARTUCHOS),.22 LR,M,Cidadão,1
4,1965,1,MG,CAPINÓPOLIS,Ativo/Válido,Revolver,TAURUS ARMAS S.A.,.32,M,Servidor Público(Porte por prerrogativa de fun...,1
...,...,...,...,...,...,...,...,...,...,...,...
205067,2004,12,TO,ARAGUAÍNA,Vencido,Pistola,TAURUS ARMAS S.A.,.380,M,Servidor Público(Porte por prerrogativa de fun...,1
205068,2004,12,TO,PALMAS,Vencido,Pistola,TAURUS ARMAS S.A.,.380,M,Cidadão,1
205069,2004,12,TO,PALMAS,Ativo/Válido,Revolver,ROSSI (AMADEO ROSSI S.A.),.38,M,Cidadão,1
205070,2004,12,TO,PALMAS,Vencido,Revolver,ROSSI (AMADEO ROSSI S.A.),.38,M,Cidadão,2
205071,2004,12,TO,PORTO NACIONAL,Ativo/Válido,Revolver,ROSSI (AMADEO ROSSI S.A.),.38,M,Cidadão,2

Verificando quantos valores faltantes tem por atributo:

In [5]:
data.isna().sum()

ANO_EMISSAO        0
MES_MISSAO         0
UF                 0
MUNICIPIO          0
STATUS_REGISTRO    0
ESPECIE_ARMA       0
MARCA_ARMA         0
CALIBRE_ARMA       0
SEXO               0
CATEGORIA          0
TOTAL              0
dtype: int64

Identificando quantas amostras e atributos existe no conjunto de dados:

In [6]:
print(f"O conjunto de dados possui {data.shape[0]} amostras e {data.shape[1]} atributos.")

O conjunto de dados possui 205072 amostras e 11 atributos.

Obtendo os atributos e os tipos de dados

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205072 entries, 0 to 205071
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ANO_EMISSAO      205072 non-null  int64
 1   MES_MISSAO       205072 non-null  int64
 2   UF               205072 non-null  object
 3   MUNICIPIO        205072 non-null  object
 4   STATUS_REGISTRO  205072 non-null  object
 5   ESPECIE_ARMA     205072 non-null  object
 6   MARCA_ARMA       205072 non-null  object
 7   CALIBRE_ARMA     205072 non-null  object
 8   SEXO             205072 non-null  object
 9   CATEGORIA        205072 non-null  object
 10  TOTAL            205072 non-null  int64
dtypes: int64(3), object(8)
memory usage: 17.2+ MB